import React, { useState } from 'react';
import { FaCheck, FaArrowRight, FaCopy, FaDownload } from 'react-icons/fa';
import './CodeComparison.css';

function CodeComparison({ originalCode, issues, onApplyFix }) {
  const [fixedCode, setFixedCode] = useState('');
  const [selectedFixes, setSelectedFixes] = useState(new Set());
  const [showComparison, setShowComparison] = useState(false);

  const applyFixes = () => {
    let code = originalCode;
    const lines = code.split('\n');
    
    // Apply selected fixes
    selectedFixes.forEach(issueId => {
      const issue = issues.find(i => i.issue_id === issueId);
      if (issue && issue.suggested_fix) {
        // Simple fix application (can be enhanced)
        const lineIndex = issue.line - 1;
        if (lineIndex >= 0 && lineIndex < lines.length) {
          // This is a simplified version - in production, you'd parse the fix better
          lines[lineIndex] = `${lines[lineIndex]}  # Fixed: ${issue.symbol}`;
        }
      }
    });
    
    const fixed = lines.join('\n');
    setFixedCode(fixed);
    setShowComparison(true);
    
    if (onApplyFix) {
      onApplyFix(fixed);
    }
  };

  const toggleFix = (issueId) => {
    const newSelected = new Set(selectedFixes);
    if (newSelected.has(issueId)) {
      newSelected.delete(issueId);
    } else {
      newSelected.add(issueId);
    }
    setSelectedFixes(newSelected);
  };

  const selectAllFixes = () => {
    setSelectedFixes(new Set(issues.map(i => i.issue_id)));
  };

  const clearSelection = () => {
    setSelectedFixes(new Set());
  };

  const copyFixedCode = () => {
    navigator.clipboard.writeText(fixedCode);
  };

  const downloadComparison = () => {
    const content = `# Code Comparison Report

## Original Code
\`\`\`
${originalCode}
\`\`\`

## Fixed Code
\`\`\`
${fixedCode}
\`\`\`

## Applied Fixes (${selectedFixes.size})
${Array.from(selectedFixes).map(id => {
  const issue = issues.find(i => i.issue_id === id);
  return `- Line ${issue.line}: ${issue.message}`;
}).join('\n')}

Generated by CodeSage AI
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `code-comparison-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (issues.length === 0) {
    return null;
  }

  return (
    <div className="code-comparison-container">
      <div className="comparison-header">
        <h2>🔧 Apply Fixes</h2>
        <p>Select issues to fix automatically</p>
      </div>

      {!showComparison ? (
        <div className="fix-selection">
          <div className="selection-controls">
            <button className="btn-select-all" onClick={selectAllFixes}>
              Select All ({issues.length})
            </button>
            <button className="btn-clear" onClick={clearSelection}>
              Clear
            </button>
            <button 
              className="btn-apply-fixes"
              onClick={applyFixes}
              disabled={selectedFixes.size === 0}
            >
              Apply {selectedFixes.size} Fix{selectedFixes.size !== 1 ? 'es' : ''}
            </button>
          </div>

          <div className="fixes-list">
            {issues.map((issue) => (
              <div 
                key={issue.issue_id}
                className={`fix-item ${selectedFixes.has(issue.issue_id) ? 'selected' : ''}`}
                onClick={() => toggleFix(issue.issue_id)}
              >
                <div className="fix-checkbox">
                  {selectedFixes.has(issue.issue_id) && <FaCheck />}
                </div>
                <div className="fix-details">
                  <div className="fix-header">
                    <span className={`fix-type fix-type-${issue.type}`}>
                      {issue.type}
                    </span>
                    <span className="fix-line">Line {issue.line}</span>
                  </div>
                  <p className="fix-message">{issue.message}</p>
                  <p className="fix-suggestion">{issue.suggested_fix}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="comparison-view">
          <div className="comparison-actions">
            <button className="btn-secondary" onClick={() => setShowComparison(false)}>
              ← Back to Selection
            </button>
            <button className="btn-icon" onClick={copyFixedCode} title="Copy fixed code">
              <FaCopy /> Copy
            </button>
            <button className="btn-icon" onClick={downloadComparison} title="Download comparison">
              <FaDownload /> Download
            </button>
          </div>

          <div className="comparison-stats">
            <div className="stat-card">
              <div className="stat-label">Issues Fixed</div>
              <div className="stat-value">{selectedFixes.size}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Original Issues</div>
              <div className="stat-value">{issues.length}</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Improvement</div>
              <div className="stat-value">
                {Math.round((selectedFixes.size / issues.length) * 100)}%
              </div>
            </div>
          </div>

          <div className="code-diff">
            <div className="diff-panel">
              <div className="diff-header">
                <h3>Original Code</h3>
                <span className="diff-badge badge-before">Before</span>
              </div>
              <pre className="code-block original">{originalCode}</pre>
            </div>

            <div className="diff-arrow">
              <FaArrowRight />
            </div>

            <div className="diff-panel">
              <div className="diff-header">
                <h3>Fixed Code</h3>
                <span className="diff-badge badge-after">After</span>
              </div>
              <pre className="code-block fixed">{fixedCode}</pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default CodeComparison;
