import { useState, useEffect } from 'react';
import { FaCode, FaCalendar, FaExclamationTriangle, FaTrash, FaEye, FaDownload, FaSearch } from 'react-icons/fa';
import './History.css';

function History() {
  const [reviews, setReviews] = useState([]);
  const [filteredReviews, setFilteredReviews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReview, setSelectedReview] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('all');

  useEffect(() => {
    fetchHistory();
  }, []);

  useEffect(() => {
    filterReviews();
  }, [searchTerm, filterType, reviews]);

  const fetchHistory = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await fetch('http://localhost:8000/history', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      const data = await response.json();
      setReviews(data.reviews);
      setFilteredReviews(data.reviews);
    } catch (error) {
      console.error('Error fetching history:', error);
    } finally {
      setLoading(false);
    }
  };

  const filterReviews = () => {
    let filtered = [...reviews];

    // Search filter
    if (searchTerm) {
      filtered = filtered.filter(review => 
        review.code.toLowerCase().includes(searchTerm.toLowerCase()) ||
        review.language.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    // Type filter
    if (filterType !== 'all') {
      filtered = filtered.filter(review => {
        if (filterType === 'no-issues') return review.total_issues === 0;
        if (filterType === 'has-issues') return review.total_issues > 0;
        if (filterType === 'high-issues') return review.total_issues >= 5;
        return true;
      });
    }

    setFilteredReviews(filtered);
  };

  const viewReview = async (reviewId) => {
    try {
      const token = localStorage.getItem('token');
      const response = await fetch(`http://localhost:8000/history/${reviewId}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      const data = await response.json();
      setSelectedReview(data);
    } catch (error) {
      console.error('Error fetching review:', error);
    }
  };

  const deleteReview = async (reviewId) => {
    if (!window.confirm('Are you sure you want to delete this review?')) return;

    try {
      const token = localStorage.getItem('token');
      await fetch(`http://localhost:8000/history/${reviewId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      fetchHistory();
    } catch (error) {
      console.error('Error deleting review:', error);
    }
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString() + ' ' + date.toLocaleTimeString();
  };

  const exportAsText = (review) => {
    const content = `
CodeSage AI - Code Review Report
================================
Date: ${formatDate(review.created_at)}
Language: ${review.language}
Total Issues: ${review.total_issues}

CODE:
${'-'.repeat(50)}
${review.code}
${'-'.repeat(50)}

ISSUES FOUND:
${review.issues.map((issue, index) => `
${index + 1}. ${issue.type.toUpperCase()} - Line ${issue.line}
   Message: ${issue.message}
   Explanation: ${issue.explanation}
   ${issue.suggested_fix ? `Suggested Fix: ${issue.suggested_fix}` : ''}
`).join('\n')}

Generated by CodeSage AI
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codesage-review-${new Date(review.created_at).toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportAsMarkdown = (review) => {
    const content = `
# CodeSage AI - Code Review Report

**Date:** ${formatDate(review.created_at)}  
**Language:** ${review.language}  
**Total Issues:** ${review.total_issues}

## Code

\`\`\`${review.language}
${review.code}
\`\`\`

## Issues Found

${review.issues.map((issue, index) => `
### ${index + 1}. ${issue.type.toUpperCase()} - Line ${issue.line}

**Message:** ${issue.message}

**Explanation:** ${issue.explanation}

${issue.suggested_fix ? `**Suggested Fix:** ${issue.suggested_fix}` : ''}

---
`).join('\n')}

*Generated by CodeSage AI*
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codesage-review-${new Date(review.created_at).toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return <div className="history-loading">Loading history...</div>;
  }

  if (selectedReview) {
    return (
      <div className="review-detail">
        <button className="back-btn" onClick={() => setSelectedReview(null)}>
          ← Back to History
        </button>
        <div className="review-detail-header">
          <h2>Review Details</h2>
          <div className="review-actions">
            <button className="export-btn" onClick={() => exportAsText(selectedReview)}>
              <FaDownload /> Export as Text
            </button>
            <button className="export-btn markdown" onClick={() => exportAsMarkdown(selectedReview)}>
              <FaDownload /> Export as Markdown
            </button>
          </div>
          <p className="review-date">
            <FaCalendar /> {formatDate(selectedReview.created_at)}
          </p>
        </div>
        <div className="review-code">
          <h3><FaCode /> Code</h3>
          <pre>{selectedReview.code}</pre>
        </div>
        <div className="review-issues">
          <h3><FaExclamationTriangle /> Issues Found: {selectedReview.total_issues}</h3>
          {selectedReview.issues.map((issue, index) => (
            <div key={index} className={`issue-item issue-${issue.type}`}>
              <div className="issue-header">
                <span className="issue-type">{issue.type}</span>
                <span className="issue-line">Line {issue.line}</span>
              </div>
              <p className="issue-message">{issue.message}</p>
              <p className="issue-explanation">{issue.explanation}</p>
              {issue.suggested_fix && (
                <div className="issue-fix">
                  <strong>Suggested Fix:</strong>
                  <p>{issue.suggested_fix}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="history-container">
      <div className="history-header">
        <h2>Code Review History</h2>
        <p>View your past code reviews and analysis results</p>
      </div>

      {/* Search and Filter */}
      <div className="history-controls">
        <div className="search-box">
          <FaSearch className="search-icon" />
          <input
            type="text"
            placeholder="Search by code or language..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>
        <select 
          className="filter-select"
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
        >
          <option value="all">All Reviews</option>
          <option value="no-issues">No Issues</option>
          <option value="has-issues">Has Issues</option>
          <option value="high-issues">5+ Issues</option>
        </select>
      </div>

      {filteredReviews.length === 0 ? (
        <div className="no-history">
          <FaCode className="no-history-icon" />
          <h3>{reviews.length === 0 ? 'No Reviews Yet' : 'No Results Found'}</h3>
          <p>{reviews.length === 0 ? 'Start analyzing code to build your review history' : 'Try adjusting your search or filter'}</p>
        </div>
      ) : (
        <div className="history-list">
          {filteredReviews.map((review) => (
            <div key={review.id} className="history-card">
              <div className="history-card-header">
                <div className="history-info">
                  <FaCalendar className="history-icon" />
                  <span>{formatDate(review.created_at)}</span>
                </div>
                <div className="history-actions">
                  <button 
                    className="view-btn"
                    onClick={() => viewReview(review.id)}
                    title="View Details"
                  >
                    <FaEye />
                  </button>
                  <button 
                    className="delete-btn"
                    onClick={() => deleteReview(review.id)}
                    title="Delete"
                  >
                    <FaTrash />
                  </button>
                </div>
              </div>
              <div className="history-card-body">
                <div className="history-stat">
                  <FaExclamationTriangle className="stat-icon" />
                  <span>{review.total_issues} issues found</span>
                </div>
                <div className="history-stat">
                  <FaCode className="stat-icon" />
                  <span>{review.language}</span>
                </div>
              </div>
              <div className="history-code-preview">
                <pre>{review.code.substring(0, 150)}...</pre>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default History;
